# Generated by Django 5.1.3 on 2024-11-20 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IEauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ieuser',
            old_name='realname',
            new_name='username',
        ),
    ]
